openapi: 3.0.0
info:
  description: Service that helps choosing a cryptocurrency to invest in.
  version: '1.0'
  title: Crypto Recommendations Service
tags:
  - name: Recommendation
paths:
  '/cryptos-desc':
    get:
      tags:
        - Recommendation
      summary: Gets cryptos in descending order.
      description: >-
        Returns the available currencies in descending order, ordered by their normalized range.
      responses:
        '200':
          description: >-
            Successful request.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoinResponse'
                  
  '/cryptos/{name}':
    get:
      tags:
        - Recommendation
      summary: Gets details about the selected crypto.
      description: >-
        Returns the oldest, newest, maximum, minimum price of the selected currency.
      operationId: searchAppointmentAvailabilities
      parameters:
        - name: name
          in: path
          description: Name of a cryptocurrency.
          required: true
          schema:
              type: string
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinResponse'
        '404':
          description: This crypto is not supported yet.
                
  '/cryptos/day':
    get:
      tags:
        - Recommendation
      summary: Gets the currency that has the maximum normalized range for the given day.
      parameters:
        - name: date
          in: query
          description: the date in yyyy-MM-dd format.
          required: true
          schema:
              type: string
      responses:
        '200':
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoinResponse'
 
components:
  schemas:
    CoinResponse:
      type: object
      properties:
        name:
          type: string
          description: name of the currency.
        details:
          allOf:
            - $ref: '#/components/schemas/Details'
    Details:
      type: object
      properties:
        oldestValue:
          type: number
          format: double
          description: oldest price of the currency.
        newestValue:
          type: number
          format: double
          description: newest price of the currency.
        maxValue:
          type: number
          format: double
          description: maximum price of the currency.
        minValue:
          type: number
          format: double
          description: minimum price of the currency.